name: Build and Deploy Frontend

#on:
#  push:
#    branches:
#     - main
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image - ${GITHUB_REF#refs/tags/}
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build . -t ghcr.io/omerfkara/rushaan_fe:${IMAGE_TAG}
#      - name: Build Docker image
#        run: |
#          docker build . -t ghcr.io/omerfkara/rushaan_fe:latest
      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/omerfkara/rushaan_fe:${IMAGE_TAG}   

#      - name: Push Docker image
#        run: |
#          docker push ghcr.io/omerfkara/rushaan_fe:latest


      - name: Update deployment with new image
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          sed -i'' "s|image: .*|image: ghcr.io/omerfkara/rushaan_fe:${IMAGE_TAG}|" k8s/deployment.yaml
  
#      - name: Update Kubernetes deployment manifest with new image
#        run: |
#          sed -i 's|image: .*|image: ghcr.io/omerfkara/rushaan_fe:latest|' k8s/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "CI: update image tag"
          git push
